// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5qs63VjPxcEizUd63r6R1L4IhN2T445Y',
    appId: '1:244104968868:web:274b6c512c4e97a6a88431',
    messagingSenderId: '244104968868',
    projectId: 'yucheng-guan',
    authDomain: 'yucheng-guan.firebaseapp.com',
    storageBucket: 'yucheng-guan.firebasestorage.app',
    measurementId: 'G-9D679Z6TM6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTYq5CYGF6D33GfSfy-DQdZdN7gqDBAyI',
    appId: '1:244104968868:android:dc03b7623c7ab2d2a88431',
    messagingSenderId: '244104968868',
    projectId: 'yucheng-guan',
    storageBucket: 'yucheng-guan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLQor39T3aPXgdt9gU3wwb-AhM_Kwbv-0',
    appId: '1:244104968868:ios:0cbb0791d2717ecfa88431',
    messagingSenderId: '244104968868',
    projectId: 'yucheng-guan',
    storageBucket: 'yucheng-guan.firebasestorage.app',
    iosClientId: '244104968868-s29kmmo8jpkdgcfs88kp49nqeodkng0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.garageSale',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLQor39T3aPXgdt9gU3wwb-AhM_Kwbv-0',
    appId: '1:244104968868:ios:0cbb0791d2717ecfa88431',
    messagingSenderId: '244104968868',
    projectId: 'yucheng-guan',
    storageBucket: 'yucheng-guan.firebasestorage.app',
    iosClientId: '244104968868-s29kmmo8jpkdgcfs88kp49nqeodkng0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.garageSale',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5qs63VjPxcEizUd63r6R1L4IhN2T445Y',
    appId: '1:244104968868:web:3e0143b475b27d08a88431',
    messagingSenderId: '244104968868',
    projectId: 'yucheng-guan',
    authDomain: 'yucheng-guan.firebaseapp.com',
    storageBucket: 'yucheng-guan.firebasestorage.app',
    measurementId: 'G-QNZXVRM9KV',
  );
}